spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: Pass2020!
  transaction.default-timeout: 600s
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

auth:
  username: ''
  password: ''

logging.level:
  root: info
  com.example.be: debug
  com.zaxxer.hikari.HikariConfig: DEBUG
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{5}.%M - %msg%n'

storage:
  type: local
  path: share
  subpath: subfolder
  useIdAsName: true
  encryption: true